name: IggDrasil Classe Plugin
version: 1.0
author: augma
main: com.augma.iggdrasilclassplugin.Main
depend: [ArmorEquipEvent]
commands:
  resetclasse:
    description: Permet de reset completement les point d attribut d un joueur et sa classe
    permission: iggdrasilclasse.admin
  infoclasse:
    description: Permet de voir la description de la classe d un joueur
    permission: iggdrasilclasse.admin
  classrequierement:
    description: Permet d appliquer une restriction sur les epee et armure
    permission: iggdrasilclasse.admin
  removerequierement:
    description: Permet de supprimer les restrictions sur les epees et armures
    permission: iggdrasilclasse.admin